apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetes-demo-proxy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kubernetes-demo-proxy
  resources:
    requests:
      storage: 1Gi