apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-webapplication
namePrefix: prod-
bases:
 - ../../application
 - ../../infrastructure

patchesStrategicMerge:
  - webapplication.yml
  - ingress.yml

resources:
  - namespace.yml