apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-webapplication
namePrefix: demo-
bases:
 - ../../application
 - ../../infrastructure

patchesStrategicMerge:
  - webapplication.yml
  - ingress.yml
  - pvc.yaml

resources:
  - namespace.yml