apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubernetes-demo-proxy
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: kubernetes-demo-proxy
  local:
    path: /data/containers/kubernetes/test01
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - fileserver
